// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SimpleErpApi.Migrations
{
    [DbContext(typeof(SimpleErpContext))]
    partial class SimpleErpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleErpApi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoIdentificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("documento_identificador");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentificacao")
                        .IsUnique()
                        .HasDatabaseName("IX_Clientes_DocumentoIdentificacao_UNIQUE");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("SimpleErpApi.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("COFINS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cofins");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_emissao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<decimal>("ICMS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("icms");

                    b.Property<decimal>("IPI")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ipi");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("int")
                        .HasColumnName("numero_documento");

                    b.Property<decimal>("PIS")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pis");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("TipoId")
                        .HasColumnType("int")
                        .HasColumnName("tipo_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique()
                        .HasDatabaseName("IX_NotasFiscais_NumeroDocumento_UNIQUE");

                    b.HasIndex("StatusId");

                    b.HasIndex("TipoId");

                    b.ToTable("notas_fiscais");
                });

            modelBuilder.Entity("SimpleErpApi.Models.NotaFiscalProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int")
                        .HasColumnName("nota_fiscal_id");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("notas_fiscais_produtos");
                });

            modelBuilder.Entity("SimpleErpApi.Models.NotaFiscalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("notas_fiscais_status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Rascunho da nota fiscal (Ainda pode ser alterado e excluido)",
                            Nome = "RASCUNHO"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Nota fiscal lançada (Não pode mais ser alterada ou excluida)",
                            Nome = "LANÇADA"
                        });
                });

            modelBuilder.Entity("SimpleErpApi.Models.NotaFiscalTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("notas_fiscais_tipos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Nota fiscal de entrada (compra)",
                            Nome = "ENTRADA"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Nota fiscal de saída (venda)",
                            Nome = "SAÍDA"
                        });
                });

            modelBuilder.Entity("SimpleErpApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("SimpleErpApi.Models.NotaFiscal", b =>
                {
                    b.HasOne("SimpleErpApi.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleErpApi.Models.NotaFiscalStatus", "NotaFiscalStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleErpApi.Models.NotaFiscalTipo", "NotaFiscalTipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("NotaFiscalStatus");

                    b.Navigation("NotaFiscalTipo");
                });

            modelBuilder.Entity("SimpleErpApi.Models.NotaFiscalProduto", b =>
                {
                    b.HasOne("SimpleErpApi.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleErpApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaFiscal");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
